#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ -d "venv" ]; then
  source venv/bin/activate
else
  if [ -x "$(command -v uv)" ]; then
    uv venv venv
  else
    python3 -m venv venv
  fi
  source venv/bin/activate
  python -m ensurepip --upgrade
fi

if ! [ -x "$(command -v uv)" ]; then
  python -m pip install uv
fi

# Install runtime + test + dev dependencies
python -m pip install --requirement requirements.test.txt
python -m pip install --requirement requirements-dev.txt

# Install pre-commit hooks
if [ -f ".pre-commit-config.yaml" ]; then
    pre-commit install
fi
